# Generated by Django 4.2.13 on 2024-06-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "cc_no",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("cc_content", models.CharField(max_length=100)),
                ("cc_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "d_name",
                    models.CharField(
                        db_index=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("d_presc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IdentityInfo",
            fields=[
                (
                    "no",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("belong", models.CharField(db_index=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("p_index", models.IntegerField(primary_key=True, serialize=False)),
                ("p_no", models.CharField(max_length=2)),
                ("p_depict", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "f_no",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("f_score", models.IntegerField()),
                ("f_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SeaSurfaceHeight",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("ssh", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryAssist",
            fields=[
                (
                    "no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="common.identityinfo",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="common.identityinfo",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("s_profession", models.CharField(max_length=60)),
                ("s_depart", models.CharField(db_index=True, max_length=20)),
                ("s_index", models.DecimalField(decimal_places=2, max_digits=10)),
                ("s_time_begin", models.IntegerField()),
                ("s_time_end", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="common.identityinfo",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("v_age", models.IntegerField()),
                ("v_gender", models.CharField(max_length=6)),
                ("v_aim", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cs_time", models.DateField(db_index=True)),
                ("content", models.CharField(max_length=100)),
                (
                    "cr_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cr",
                        to="common.identityinfo",
                    ),
                ),
                (
                    "cs_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cs",
                        to="common.identityinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.score"
                    ),
                ),
                ("no", models.ManyToManyField(to="common.visitor")),
            ],
        ),
        migrations.AddField(
            model_name="score",
            name="no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.staff"
            ),
        ),
        migrations.CreateModel(
            name="Current_Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_index", models.IntegerField(db_index=True)),
                ("a_date", models.DateField(db_index=True)),
                (
                    "a_no_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cc_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.comment"
                    ),
                ),
                ("no", models.ManyToManyField(to="common.visitor")),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.staff"
            ),
        ),
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Au_num", models.IntegerField()),
                ("Au_index", models.IntegerField(db_index=True)),
                ("Au_date", models.DateField(db_index=True)),
                (
                    "d_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.dataset"
                    ),
                ),
                ("Au_no", models.ManyToManyField(to="common.visitor")),
            ],
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_index", models.IntegerField(db_index=True)),
                ("a_date", models.DateField(db_index=True)),
                (
                    "a_no_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.staff",
                    ),
                ),
                (
                    "a_no_visitor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.visitor",
                    ),
                ),
            ],
        ),
    ]
